### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by faxotherapy** [ssh-vault/ssh-vault#34]
Hi,

I can't use my pub key with *ssh-vault*:
```shell
$ echo "secret" | ssh-vault -k ~/.ssh/id_ed25519.pub create vault.ssh
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/ssh-vault/ssh-vault/vendor/github.com/ssh-vault/ssh2pem.readLength(0xc4200ac093, 0x0, 0x0, 0xc400000020, 0xc4200ac093, 0x0, 0x0, 0xc4201263a0, 0x0)
	/private/tmp/ssh-vault-20180607-10777-oxbbo1/src/github.com/ssh-vault/ssh-vault/vendor/github.com/ssh-vault/ssh2pem/ssh2pem.go:20 +0x19b
github.com/ssh-vault/ssh-vault/vendor/github.com/ssh-vault/ssh2pem.getRsaValues(0xc4200ac084, 0x2f, 0x2f, 0xc4200ac080, 0x33, 0x33, 0x0, 0x0, 0xc)
	/private/tmp/ssh-vault-20180607-10777-oxbbo1/src/github.com/ssh-vault/ssh-vault/vendor/github.com/ssh-vault/ssh2pem/ssh2pem.go:59 +0x18a
github.com/ssh-vault/ssh-vault/vendor/github.com/ssh-vault/ssh2pem.DecodePublicKey(0xc4201481c0, 0x64, 0x0, 0x5000d90, 0x0, 0x0)
	/private/tmp/ssh-vault-20180607-10777-oxbbo1/src/github.com/ssh-vault/ssh-vault/vendor/github.com/ssh-vault/ssh2pem/ssh2pem.go:86 +0xde
github.com/ssh-vault/ssh-vault/vendor/github.com/ssh-vault/ssh2pem.GetPublicKeyPem(0xc4201481c0, 0x64, 0x64, 0x64, 0xc4201481c0, 0x64, 0x64)
	/private/tmp/ssh-vault-20180607-10777-oxbbo1/src/github.com/ssh-vault/ssh-vault/vendor/github.com/ssh-vault/ssh2pem/ssh2pem.go:155 +0x42
github.com/ssh-vault/ssh-vault/vendor/github.com/ssh-vault/ssh2pem.GetPem(0x7fff5fbff905, 0x23, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/ssh-vault-20180607-10777-oxbbo1/src/github.com/ssh-vault/ssh-vault/vendor/github.com/ssh-vault/ssh2pem/ssh2pem.go:146 +0x361
github.com/ssh-vault/ssh-vault.(*vault).PKCS8(0xc4200be3c0, 0x0, 0x7fff5fbff905, 0x23)
	/private/tmp/ssh-vault-20180607-10777-oxbbo1/src/github.com/ssh-vault/ssh-vault/vault.go:77 +0x3c
main.main()
	/private/tmp/ssh-vault-20180607-10777-oxbbo1/src/github.com/ssh-vault/ssh-vault/cmd/ssh-vault/main.go:109 +0x518
```

**Comment by nbari** [comment]
Currently only rsa keys supported https://github.com/ssh-vault/ssh-vault/issues/18
